"""
Douyin Account Login Helper — VideoDubberPro
Mở trình duyệt trực quan (Google Chrome / Chromium) để người dùng quét mã QR hoặc đăng nhập Douyin.
Tự động xuất cookies ra config/ và temp/ để hệ thống tải video độ phân giải cao nhất (1080p/2K/4K).
"""
import os, sys, json, time

if sys.platform == 'win32':
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COOKIE_CONFIG_JSON = os.path.join(BASE_DIR, "config", "douyin_cookies.json")
COOKIE_CONFIG_TXT  = os.path.join(BASE_DIR, "config", "douyin_cookies.txt")
COOKIE_TEMP_JSON   = os.path.join(BASE_DIR, "temp", "douyin_cookies.json")
COOKIE_TEMP_TXT    = os.path.join(BASE_DIR, "temp", "douyin_cookies.txt")

os.makedirs(os.path.join(BASE_DIR, "config"), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, "temp"), exist_ok=True)

def export_netscape_cookies(cookies, txt_path):
    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by VideoDubberPro Douyin Login Helper\n")
        for c in cookies:
            domain = c.get('domain', '')
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            path = c.get('path', '/')
            secure = "TRUE" if c.get('secure') else "FALSE"
            expiry = str(int(c.get('expires', time.time() + 365*86400)))
            name = c.get('name', '')
            val = c.get('value', '')
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{val}\n")

def save_all_cookies(all_cookies):
    # Save JSON
    with open(COOKIE_CONFIG_JSON, 'w', encoding='utf-8') as f:
        json.dump(all_cookies, f, indent=2, ensure_ascii=False)
    with open(COOKIE_TEMP_JSON, 'w', encoding='utf-8') as f:
        json.dump(all_cookies, f, indent=2, ensure_ascii=False)
        
    # Save Netscape TXT
    export_netscape_cookies(all_cookies, COOKIE_CONFIG_TXT)
    export_netscape_cookies(all_cookies, COOKIE_TEMP_TXT)

def login():
    print("=" * 65)
    print("      VIDEO DUBBER PRO — TIỆN ÍCH ĐĂNG NHẬP DOUYIN (TIKTOK TRUNG)")
    print("=" * 65)
    print("1. Đang khởi động trình duyệt Chrome trực quan trên màn hình...")
    print("2. Khi cửa sổ mở lên:")
    print("   - Nếu gặp thanh trượt ghép hình (Captcha): Kéo thanh trượt để qua.")
    print("   - Mở app Douyin trên điện thoại -> Quét mã QR đăng nhập.")
    print("   - Hoặc đăng nhập bằng SĐT / Mật khẩu trực tiếp.")
    print("3. Hệ thống sẽ TỰ ĐỘNG phát hiện khi đăng nhập thành công và lưu cookies!")
    print("=" * 65)

    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = None
        launch_args = [
            '--disable-blink-features=AutomationControlled',
            '--start-maximized',
            '--no-default-browser-check',
            '--no-first-run'
        ]
        
        # Try real Chrome first, fallback to bundled Chromium
        try:
            browser = p.chromium.launch(
                channel="chrome",
                headless=False,
                args=launch_args,
                ignore_default_args=['--enable-automation']
            )
            print("[INFO] Đã khởi động Google Chrome thực tế.")
        except Exception as e:
            print(f"[INFO] Chuyển sang Chromium dự phòng: {e}")
            browser = p.chromium.launch(
                headless=False,
                args=launch_args,
                ignore_default_args=['--enable-automation']
            )

        context = browser.new_context(
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
            no_viewport=True,
            locale='zh-CN'
        )

        page = context.new_page()
        print("[INFO] Đang tải trang chủ Douyin...")
        try:
            page.goto("https://www.douyin.com", wait_until='commit', timeout=60000)
        except Exception as e:
            print(f"[Cảnh báo] Lỗi tải ban đầu: {e}")

        print("[CHỜ ĐĂNG NHẬP] Trình duyệt đã mở. Vui lòng quét mã QR hoặc đăng nhập trên cửa sổ Chrome...")

        logged_in = False
        start_time = time.time()
        
        while time.time() - start_time < 300: # 5 minutes timeout
            try:
                # Check if browser was closed by user
                if page.is_closed() or len(context.pages) == 0:
                    print("[INFO] Người dùng đã đóng cửa sổ trình duyệt.")
                    break

                cookies = context.cookies()
                c_map = {c['name']: c.get('value', '') for c in cookies}

                # Authentication indicator cookies for Douyin
                has_session = (
                    ('sessionid' in c_map and len(c_map['sessionid']) > 5) or
                    ('sessionid_ss' in c_map and len(c_map['sessionid_ss']) > 5) or
                    ('passport_auth_status' in c_map and c_map['passport_auth_status'] in ('verified', '1')) or
                    ('sid_guard' in c_map and len(c_map['sid_guard']) > 5) or
                    ('uid_tt' in c_map and len(c_map['uid_tt']) > 0)
                )

                if has_session:
                    logged_in = True
                    break
            except Exception:
                pass

            time.sleep(1)

        if logged_in:
            print("\n" + "=" * 65)
            print("🎉 [XÁC NHẬN] ĐĂNG NHẬP THÀNH CÔNG!")
            print("=" * 65)
            all_cookies = context.cookies()
            save_all_cookies(all_cookies)
            print(f"✅ Đã lưu cấu hình Cookie JSON: {COOKIE_CONFIG_JSON}")
            print(f"✅ Đã lưu cấu hình Cookie TXT:  {COOKIE_CONFIG_TXT}")
            print("✨ Từ bây giờ, VideoDubberPro sẽ tự động tải video Douyin ở chất lượng cao nhất!")
            print("Cửa sổ Chrome sẽ tự động đóng sau 3 giây.")
            time.sleep(3)
        else:
            # Check one last time before exiting
            try:
                cookies = context.cookies()
                c_map = {c['name']: c.get('value', '') for c in cookies}
                if ('sessionid' in c_map and len(c_map['sessionid']) > 5) or ('sessionid_ss' in c_map and len(c_map['sessionid_ss']) > 5):
                    print("\n🎉 [XÁC NHẬN] Đã tìm thấy sessionid! Lưu cookie...")
                    save_all_cookies(cookies)
                else:
                    print("\n[HẾT GIỜ] Chưa hoàn tất đăng nhập hoặc đã đóng trình duyệt.")
            except Exception:
                pass

        try:
            browser.close()
        except Exception:
            pass

if __name__ == "__main__":
    login()

